version: '3.9'

services:
    web:
        image: ${DOCKER_REGISTRY-}web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
           - "5000:80"
        depends_on:
           - "db"
        environment:
            POSTGRES_HOST: "db"
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD : $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD : $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        volumes:
            - scc-volume:/var/lib/postgresql/data
        
volumes:
  scc-volume: